name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a9681f3b6d32ea3a1dad5ea764892d12453d1461408bc69280891596985746b"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
