name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6af0d7bfe8d3848570b868be22e5576aaf78ea86ba08d26c6b4a96cc413af682"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
