name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7ea9b97cc9a1a43b0339e29a34f7d641e1e0552fb5a494a4f1e921a418a6b70"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
