name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1ccbeb806293f2e1c87f7ee87f789368747de01b07ccc87cdc80d179b1ae01f"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
