name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d13e081d793d1f83b43c6af1744d888a769f77cef38e7c495be37c01a6458c88"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
