name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "359f468a02fb0b94b514b02b5d13ea05f31eb75875dcb5e5721328bd97587487"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
