name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2d568b326e476c7ae617cfbed7dcb4cd42378a1f65779269a34e338d2104bc0"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
