name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d97d76d8b5d140ac86b10cf9eb23b60d103a9892e1e332e65192237054d172b"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
