name = "Cozy Pack"
author = "Faer-Anne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3764433f7eeabbcaa5e0d4157f692b2809e0d2dc282174d50a6bde9f951ab2e8"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
